Add support for measuring power draw from ACs
sampsyo/hass-smartthinq pull request #52
Opened 2020-05-25 19:45 UTC by davr

Returns the power usage in Watts from the AC to home assistant as a device attribute.

Add these lines to configuration.yaml to get a graph of your AC's power usage: (note that history graph is deprecated according to HA but they don't give any clear instructions on what you're supposed to use instead, so the graph might stop working at some point in the future)

```
sensor:
    - platform: template
      sensors:
          ac_power_sensor:
              friendly_name: AC Power Usage
              value_template:
"{{states.climate.air_conditioner.attributes.power}}"
              unit_of_measurement: W

history_graph:
    power:
        name: Power Graph
        entities:
            - sensor.ac_power_sensor
```

2020-05-25 20:04 UTC, sampsyo requested changes
Looks great; thanks! The only big thing to fix here is avoiding a crash when the device doesn't support power.

2020-05-25 20:04 UTC, sampsyo commented on climate.py
> +        self._attrs = {'power':0}
Maybe this should just be `{}` initially, to indicate that no power is available, rather than misleadingly reporting "zero watts"?

2020-05-25 20:04 UTC, sampsyo commented on climate.py
> +                power = self._ac.get_power()
Not all devices can report power, unfortunately—mine can't, for instance. When I try to use this, the API raises an `InvalidRequestError`. Can we please catch that error (just for this line, not for the `poll`)?

Even better if we remember the firs time we hit this and don't keep trying every time.

2020-06-30 06:29 UTC, davr commented
made requested changes

2020-06-30 11:20 UTC, sampsyo approved these changes
Looks great; thanks!!

2020-06-30 11:20 UTC, merged